#ifndef __DTLS_CERT_H__
#define __DTLS_CERT_H__

#include <string>

/**
 * PHASE 22.2.3 (WebRTC): one self-signed certificate for the whole
 * process lifetime - NOT per-connection. WebRTC's DTLS handshake
 * (Phase 22.4, not yet implemented) doesn't validate this cert
 * against a CA the way a browser validates a website's HTTPS cert;
 * it only checks that the cert actually used during the DTLS
 * handshake matches the SHA-256 fingerprint advertised in the SDP
 * answer (`a=fingerprint:sha-256 ...`, see webrtc_sdp.h/this phase's
 * answer builder). That's WebRTC's actual trust model: "I trust
 * whichever peer I exchanged this exact fingerprint with over
 * signaling" - not a CA chain. Uses OpenSSL (this project's first use
 * of it) rather than hand-rolled crypto, per this phase's design
 * decision - see roadmap.md's Phase 22 breakdown.
 */

// Generates (once) a self-signed EC certificate + private key,
// kept in memory for the process's lifetime. Returns 0 on success,
// -1 on any OpenSSL failure (logged via LOG_ERROR).
int dtls_cert_init(void);

void dtls_cert_cleanup(void);

// Returns the SHA-256 fingerprint of the certificate generated by
// dtls_cert_init(), formatted exactly as SDP's
// "a=fingerprint:sha-256 <value>" expects: uppercase hex bytes
// colon-separated (e.g. "AB:CD:EF:..."). Empty string if
// dtls_cert_init() hasn't been called yet or failed.
std::string dtls_cert_get_fingerprint_sha256(void);

#endif // __DTLS_CERT_H__
