#ifndef __DTLS_CERT_H__
#define __DTLS_CERT_H__

#include <string>

#include <openssl/x509.h>
#include <openssl/evp.h>

/**
 * A self-signed certificate for the whole process lifetime, used for
 * the WebRTC DTLS handshake. WebRTC does not validate this against a
 * CA the way a browser validates an HTTPS certificate; instead each
 * side checks that the certificate presented during the handshake
 * matches the SHA-256 fingerprint advertised over signaling
 * (`a=fingerprint:sha-256 ...`, see webrtc_sdp.h). That fingerprint
 * check - not a CA chain - is what prevents a man-in-the-middle here.
 *
 * dtls_cert_get_cert()/_get_pkey() expose the underlying OpenSSL
 * objects for loading into an SSL_CTX (dtls_handshake.h).
 * dtls_cert_fingerprint_sha256() is generic (any X509*) so it can also
 * verify a remote peer's certificate against what was promised in its
 * SDP offer.
 */

// Generates (once) a self-signed EC certificate + private key,
// kept in memory for the process's lifetime. Returns 0 on success,
// -1 on any OpenSSL failure (logged via LOG_ERROR).
int dtls_cert_init(void);

void dtls_cert_cleanup(void);

// Returns the SHA-256 fingerprint of the certificate generated by
// dtls_cert_init(), formatted exactly as SDP's
// "a=fingerprint:sha-256 <value>" expects: uppercase hex bytes
// colon-separated (e.g. "AB:CD:EF:..."). Empty string if
// dtls_cert_init() hasn't been called yet or failed.
std::string dtls_cert_get_fingerprint_sha256(void);

// Non-owning pointers to this project's own cert/key - valid between
// dtls_cert_init() and dtls_cert_cleanup().
X509 *dtls_cert_get_cert(void);
EVP_PKEY *dtls_cert_get_pkey(void);

// Same SHA-256-fingerprint-as-SDP-string formatting as
// dtls_cert_get_fingerprint_sha256(), but for an arbitrary cert - used
// to verify a remote peer's certificate against what its SDP offer
// promised.
std::string dtls_cert_fingerprint_sha256(X509 *cert);

// Same fingerprint formatting, but using whichever hash algorithm the
// peer's own SDP offer declared (RFC 8122's "a=fingerprint:<algo> ...")
// instead of assuming SHA-256 - a peer is free to sign its own
// self-signed cert's fingerprint with any hash it likes (sha-1,
// sha-256, sha-384, sha-512 are the ones this project recognizes;
// anything else fails closed). This is what dtls_handshake.cpp must
// use to verify a remote peer's certificate: comparing a SHA-256 hash
// against a value the peer computed with, say, SHA-512 will never
// match regardless of whether the cert is genuine. Returns "" for an
// unrecognized algo name (caller should then treat verification as a
// hard failure, not fall back to any other digest).
std::string dtls_cert_fingerprint(X509 *cert, const std::string &algo_name);

#endif // __DTLS_CERT_H__
