name: C/C++ CI

on:
  push:
    branches: [ "csi_camera_streaming" ]
  pull_request:
    branches: [ "csi_camera_streaming" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (cmake, libcamera-dev)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libcamera-dev

    - name: Configure (CMake)
      run: cmake -B build

    - name: Build (camera_app + camera_receiver)
      run: cmake --build build -j$(nproc)
